services:
  server-module:
    build: ./server-module
    ports:
      - "8080:8080"

  agent-module:
    build:
      context: ./agent-module
      args:
        - QUICK_BUILD=${QUICK_BUILD:-false}
    volumes:
      - ./metrics:/app/metrics
    depends_on:
      - server-module
    environment:
      - SERVER_URL=http://server-module:8080/metrics
