# Global configuration
intervalSeconds: 1

# Collectors configuration
collectors:
  cpu: true
  memory: true

# Exporters configuration
exporters:
  logging:
    enabled: true
  webservice:
    enabled: true
    bufferSeconds: 10
    serverUrl: http://server-module:8080/metrics
